### ISSUE TITLE
Testing on Mac

### ISSUE THREAD

**Issue by Kamek** [PrimaryFeather/Sparrow-Framework#1074] opened 2012-08-31 19:53 UTC
I'd love to be able to test or possibly deploy to mac, any chance of that?

**Comment by PrimaryFeather** [comment] 2012-09-03 14:51
Hi Kamek!

This is definitely planned! After the Sparrow 2.0 release (which is already worked on), we want to add support for deployment on the Mac. Unfortunately, I can't give you a time schedule for that, though!

Best regards,
Daniel

**Comment by Kamek** [comment] 2012-09-04 02:51
Awesome, you guys keep up the good work!

**Comment by PrimaryFeather** [comment] 2013-04-04 15:28
This is actually a duplicate of #1048, so I close this.
A short update: Sparrow 2.0 is almost finished, so I'll soon start to tackle that one. Finally!

**Closed as completed by PrimaryFeather** 2013-04-04 15:28 UTC

**Comment by yderidde** [comment] 2014-04-15 15:30
Any plan to port it to OSX ? or this was cancelled ?
